version: "3.7"
services:
  web:
    image: nginx:latest
    container_name: "nginx_video"
    restart: unless-stopped
    tty: true
    ports:
      - "8282:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
    links:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    container_name: php-video
    working_dir: /var/www/html
    tty: true
    volumes:
      - ./app:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

networks:
  app-network:
    driver: bridge